#this script generates Figure S10 and S11 in Altınışık et al. 2022.

#comment out the next line and write your own path to /scripts folder.
setwd("/Users/ezgimo/Downloads/Altinisiketal2022/scripts")

library(pedsuite)
library(tidyverse)
library(patchwork)
library(ggforce)
library(MetBrewer)
library(ribd)

##Ped files were generated by using QuickPed Shiny App: https://magnusdv.shinyapps.io/quickped/

##Paternal Side

dadpedfile <- readr::read_tsv("../data/patside.ped")

dadped <- ped(id = dadpedfile$id, fid = dadpedfile$fid, mid = dadpedfile$mid, sex = dadpedfile$sex, verbose = T, reorder = T)
kinauotDad <- as.tibble(data.frame(ribd::kinship(dadped)), rownames = "inds", .name_repair = make.names) %>% 
  rename_with(~str_remove(., 'X'))
kinxDad <- as.tibble(data.frame(kinshipX(dadped)), rownames = "inds", .name_repair = make.names) %>% 
  rename_with(~str_remove(., 'X'))


dadpedcoef <- bind_rows(kinauotDad, kinxDad, .id = "id") %>%
  mutate(chr = case_when(id == 1 ~ "autosome",
                         id == 2 ~ "X")) %>%
  pivot_longer(cols = c(as.character(1:19), "21", "cay008")) %>% 
  select(-id) %>%
  group_by(grp = paste(pmax(inds, name),pmin(inds, name), chr, sep = "_")) %>%
  slice(1) %>%
  ungroup() %>%
  select(-grp) %>%
  filter(inds != name) %>%
  pivot_wider(names_from = chr, values_from = value) %>%
  left_join(., select(as.tibble(dadped), c("id","sex")), by = c("inds" = "id")) %>%
  left_join(., select(as.tibble(dadped), c("id","sex")), by = c("name" = "id"), suffix = c(".p1", ".p2")) %>%
  mutate(degree_auto = case_when(autosome == 0.5 ~ "Identical",
                                 autosome == 0.25 ~ "First Degree",
                                 autosome == 0.125 ~ "Second Degree",
                                 autosome == 0.0625 ~ "Third Degree",
                                 autosome == 0 ~ "Unrelated"),
         ellipse_val = case_when(autosome == 0.0625 & X > 0.1 ~ "yes",
                                 TRUE ~ "no"),
         cay008_inc = case_when(inds == "cay008" & sex.p2 == 2 ~ "yes",
                                name == "cay008" & sex.p1 == 2 ~ "yes", 
                                TRUE ~ "no"))

pos <- position_jitter(width = 0.001, height = 0.001,seed = 2345)

pDad <- ggplot(data = dadpedcoef,aes(autosome, X, fill = degree_auto)) +
  geom_jitter(data = filter(dadpedcoef, ellipse_val != "yes" | cay008_inc != "yes"),
              position = pos, size = 3, shape = 21) +
  geom_jitter(data = filter(dadpedcoef, ellipse_val == "yes", cay008_inc == "yes"),
              position = pos, size = 5,shape = 24, color = "black", show.legend = F, color = "red") +
  geom_point(data = NULL, x = 0.094811274, y = 0.200943222, color = "#CD0000",  inherit.aes = F,size = 3) +
  geom_errorbarh(aes(y = 0.200943222, xmin = 0.094811274 - 2*0.012242365, 
                     xmax = 0.094811274 + 2*0.012242365), inherit.aes = F, height = 0.01, color = "#CD0000") +
  geom_errorbar(aes(x = 0.094811274, ymin = 0.200943222 - 2*0.013671947, 
                    ymax = 0.200943222 + 2*0.013671947), inherit.aes = F, width = 0.005, color = "#CD0000") +
  geom_mark_hull(data = filter(dadpedcoef, ellipse_val == "yes"), show.legend = F, color = NA) +
  ggrepel::geom_text_repel(data = filter(dadpedcoef, ellipse_val == "yes", cay008_inc == "yes"), 
                           aes(label = inds), position = pos, size = 4, show.legend = F, 
                           fontface = "bold", min.segment.length = 0.001, color = "#262626") +
  geom_text(data = NULL, x = 0.094811274, y = 0.26, color = "#CD0000",  size = 4, label = c("cay008\ncay013"),
            inherit.aes = F) +
  #labs(title = "Kinship Coefficient Estimation of Paternal Side", 
  #     subtitle = "Autosomes vs X-Chromosome") +
  xlab("Autosomal theta estimation") +
  ylab("X-Chromosomal theta estimation") +
  scale_fill_manual("", values = met.brewer("Troy", 5)) +
  theme_bw() ; pDad

pedplot <- plot(dadped)

##Maternal Side

mampedfile <- readr::read_tsv("../data/matside.ped")

mamped <- ped(id = mampedfile$id, fid = mampedfile$fid, mid = mampedfile$mid, sex = mampedfile$sex, verbose = T, reorder = T)
kinauotmam <- as.tibble(data.frame(ribd::kinship(mamped)), rownames = "inds", .name_repair = make.names) %>% 
  rename_with(~str_remove(., 'X'))
kinxmam <- as.tibble(data.frame(kinshipX(mamped)), rownames = "inds", .name_repair = make.names) %>% 
  rename_with(~str_remove(., 'X'))

mampedcoef <- bind_rows(kinauotmam, kinxmam, .id = "id") %>%
  mutate(chr = case_when(id == 1 ~ "autosome",
                         id == 2 ~ "X")) %>%
  pivot_longer(cols = c(as.character(1:19), "21", "cay008")) %>% 
  select(-id) %>%
  group_by(grp = paste(pmax(inds, name),pmin(inds, name), chr, sep = "_")) %>%
  slice(1) %>%
  ungroup() %>%
  select(-grp) %>%
  filter(inds != name) %>%
  pivot_wider(names_from = chr, values_from = value) %>%
  left_join(., select(as.tibble(mamped), c("id","sex")), by = c("inds" = "id")) %>%
  left_join(., select(as.tibble(mamped), c("id","sex")), by = c("name" = "id"), suffix = c(".p1", ".p2")) %>%
  mutate(degree_auto = case_when(autosome == 0.5 ~ "Identical",
                                 autosome == 0.25 ~ "First Degree",
                                 autosome == 0.125 ~ "Second Degree",
                                 autosome == 0.0625 ~ "Third Degree",
                                 autosome == 0 ~ "Unrelated"),
         ellipse_val = case_when(autosome == 0.0625 & X > 0.1 ~ "yes",
                                 TRUE ~ "no"),
         cay008_inc = case_when(inds == "cay008" & sex.p2 == 2 ~ "yes",
                                name == "cay008" & sex.p1 == 2 ~ "yes", 
                                TRUE ~ "no"))

pMom <- ggplot(mampedcoef,aes(autosome, X, fill = degree_auto)) +
  geom_jitter(data = filter(mampedcoef, ellipse_val != "yes" | cay008_inc != "yes"),
              position = pos, size = 3, shape = 21) +
  geom_jitter(data = filter(mampedcoef, ellipse_val == "yes", cay008_inc == "yes"),
              position = pos, size = 5,shape = 24, color = "black", show.legend = F, color = "red") +
  geom_point(data = NULL, x = 0.094811274, y = 0.200943222, color = "#CD0000",  inherit.aes = F,size = 3) +
  geom_errorbarh(aes(y = 0.200943222, xmin = 0.094811274 - 2*0.012242365, 
                     xmax = 0.094811274 + 2*0.012242365), inherit.aes = F, height = 0.01, color = "#CD0000") +
  geom_errorbar(aes(x = 0.094811274, ymin = 0.200943222 - 2*0.013671947, 
                    ymax = 0.200943222 + 2*0.013671947), inherit.aes = F, width = 0.005, color = "#CD0000") +
  geom_mark_hull(data = filter(mampedcoef, ellipse_val == "yes"), show.legend = F, color = NA) +
  ggrepel::geom_text_repel(data = filter(mampedcoef, ellipse_val == "yes", cay008_inc == "yes"), 
                           aes(label = inds), position = pos, size = 4, show.legend = F, 
                           fontface = "bold", min.segment.length = 0.001, color = "#262626") +
  geom_text(data = NULL, x = 0.094811274, y = 0.26, color = "#CD0000",  size = 4, 
            label = c("cay008\ncay013"), inherit.aes = F) +
  #labs(title = "Kinship Coefficient Estimation of Maternal Side", 
  #     subtitle = "Autosomes vs X-Chromosome") +
  xlab("Autosomal theta estimation") +
  ylab("X-Chromosomal theta estimation") +
  scale_fill_manual("", values = met.brewer("Troy", 5)) +
  theme_bw() ; pMom

g <- pDad + pMom + plot_layout(guides = "collect") + plot_annotation(tag_levels = "A") & theme(legend.position = "bottom")

ggsave("../figures/FigureS11.pdf", g, 
       width = 10, height = 5)

##This creates a two-page plot
pdf("../figures/FigureS10.pdf")
plot(dadped, carrier = c(2,4,5,10,11,18,19,21), aff = "cay008",starred = c(2,4,5,10,11,18,19,21), 
     title = "Paternal Pedigree", col = list(`#CD0000` = "cay008", steelblue = c(2,4,5,10,11,18,19,21)))
plot(mamped, carrier = c(2,4,5,10,11,18,19,21), aff = "cay008",starred = c(2,4,5,10,11,18,19,21), 
     title = "Maternal Pedigree", col = list(`#CD0000` = "cay008", steelblue = c(2,4,5,10,11,18,19,21)))
dev.off()



